export const miuixProjectMap = {
  core: ["theme tokens", "text styles", "icons", "utility helpers"],
  basic: [
    "Button",
    "TextButton",
    "Card",
    "Surface",
    "Switch",
    "Checkbox",
    "RadioButton",
    "Slider",
    "RangeSlider",
    "TextField",
    "SearchBar",
    "TabRow",
    "TopAppBar",
    "Scaffold",
    "NavigationBar",
    "NavigationRail",
    "FloatingActionButton",
    "FloatingToolbar",
    "Divider",
    "ProgressIndicator",
    "NumberPicker",
    "Dropdown",
    "ColorPalette",
    "ColorPicker",
    "Snackbar",
    "PullToRefresh",
    "ScrollBar",
  ],
  overlay: ["OverlayDialog", "OverlayBottomSheet", "OverlayListPopup", "OverlayDropdownMenu"],
  window: ["WindowDialog", "WindowBottomSheet", "WindowListPopup", "WindowDropdownMenu"],
  preference: [
    "Preference",
    "ArrowPreference",
    "SwitchPreference",
    "CheckboxPreference",
    "RadioButtonPreference",
    "SliderPreference",
    "DropdownPreference",
    "SpinnerPreference",
  ],
  blur: ["BlurDefaults", "LayerBackdrop", "rememberLayerBackdrop", "rememberTiltLight"],
  shader: ["RuntimeShader", "RenderEffect", "isRuntimeShaderSupported"],
  squircle: ["SquircleDefaults", "squircleStyle", "squircleClipPath"],
  icons: ["MiuixIcons", "BasicIcons", "ExtendedIcons"],
  navigation3: ["NavDisplay", "NavDisplayTransitionEffects", "rememberNavDisplayState"],
} as const;
